### ISSUE TITLE
Glitch in adding/editing measurements from within inspection

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#76] opened 2018-02-04 13:03 UTC
When doing an inspection and adding a measurement the values default to zero and when the UI advances to next field it places cursor before the existing value.  This prohibits easy delete by backspace.  Can we control this?

**Comment by DanielCaspers** [comment] 2018-02-04 14:28
There are two things in there.

>1.  When doing an inspection and adding a measurement the values default to zero

This is flat out false. It defaults to the minimum acceptable value for the measurement. I'd have it in between, but then I'd need to default construct this value to fits within the set step size. The code is in InspectionsController.cs Line 439 if you're curious. 

> 2. when the UI advances to next field it places cursor before the existing value. This prohibits easy delete by backspace.

I've just tried this on both my tablet in chrome and desktop in Chrome. I have no idea what you mean by "when the UI advances", but every time I tap a field (usually to the right of it since the fields are full width of dialog), I always can backspace because my cursor is there. When I tab through on Chrome, the entire field is highlighted so backspace is always an option.

This sort of thing should be within the normal client side web development problem solving arena, but first you have to give me more info to reproduce. 

**Poor man's solution**
I just got to thinking that perhaps you should give techs better keyboard apps than the stock one (SwiftKey - it's free). The one I've been using for years offers the best predictive text and can learn the _phrases  you type_. It'd be useful for any internal code words or common notetaking phrases. It does a far superior job to others because it machine learns more from you than the English dictionary. 

This would also solve the problem because it gives arrow keys when you click into a number input field. 
![screenshot_20180204-082122](https://user-images.githubusercontent.com/6056563/35778540-2c04ade0-0985-11e8-9ced-6e973f2e71e5.png)

**Comment by DanielCaspers** [comment] 2018-02-10 16:22
Maybe this is all we need to do? 

Haven't played with yet.

https://css-tricks.com/snippets/javascript/move-cursor-to-end-of-input/

**Comment by DanielCaspers** [comment] 2018-02-19 00:12
@scaspers, make sure to get feedback on this as you demo next week. I'm not touching anything in the UI until you install Swiftkey on those tablets and hear what the techs have to say about it.

**Comment by DanielCaspers** [comment] 2018-03-26 23:46
@scaspers awaiting feedback from techs to know if this is actually a pain point

**Comment by DanielCaspers** [comment] 2018-04-13 03:54
@YoMurphy @scaspers Please let me know if this will still be enough of a pain point given the new default value handling in #98  to keep this in backlog.

**Comment by DanielCaspers** [comment] 2018-04-26 03:35
Closing as we are satisfied with the handling from #98.

**Closed by DanielCaspers** 2018-04-26 03:35 UTC
Labels: UI/UX, User Feedback
